In [12]:
import nltk

In [1]:
import pandas as pd

In [2]:
# reading file
with open("../data/Complete_data .txt","r") as file:
    corpus = file.read()

In [15]:
corpus = corpus.lower()

In [16]:
documents = nltk.sent_tokenize(corpus)
print(documents)

['0.1\n§ 1.the buddha: "what do you think, rahula: what is a mirror for?', '"the buddha:rahula: "for reflection, sir.', '"rahula:the buddha: "in the same way, rahula, bodily acts, verbal acts, & mental acts are to be done with repeated reflection.the buddha:"whenever you want to perform a bodily act, you should reflect on it: \'this bodily act i want to perform — would it lead to self-affliction, to the affliction of others, or to both?', "is it an unskillful bodily act, with painful consequences, painful results?'", 'if, on reflection, you know that it would lead to self-affliction, to the affliction of others, or to both; it would be an unskillful bodily act with painful consequences, painful results, then any bodily act of that sort is absolutely unfit for you to do.', 'but if on reflection you know that it would not cause affliction... it would be a skillful bodily act with happy consequences, happy results, then any bodily act of that sort is fit for you to do.', '(similarly with verbal acts & mental acts.', ')"while you are performing a bodily act, you should reflect on it: \'this bodily act i am doing — is it leading to self-affliction, to the affliction of others, or to both?', "is it an unskillful bodily act, with painful consequences, painful results?'", 'if, on reflection, you know that it is leading to self-affliction, to affliction of others, or both... you should give it up.', 'but if on reflection you know that it is not... you may continue with it.', '(similarly with verbal acts & mental acts.', ')"having performed a bodily act, you should reflect on it... if, on reflection, you know that it led to self-affliction, to the affliction of others, or to both; it was an unskillful bodily act with painful consequences, painful results, then you should confess it, reveal it, lay it open to the teacher or to a knowledgeable companion in the holy life.', 'having confessed it... you should exercise restraint in the future.', 'but if on reflection you know that it did not lead to affliction... it was a skillful bodily act with happy consequences, happy results, then you should stay mentally refreshed & joyful, training day & night in skillful mental qualities.', '(similarly with verbal acts.', ')"having performed a mental act, you should reflect on it... if, on reflection, you know that it led to self-affliction, to the affliction of others, or to both; it was an unskillful mental act with painful consequences, painful results, then you should feel horrified, humiliated, & disgusted with it.', 'feeling horrified... you should exercise restraint in the future.', 'but if on reflection you know that it did not lead to affliction... it was a skillful mental act with happy consequences, happy results, then you should stay mentally refreshed & joyful, training day & night in skillful mental qualities.', '"rahula, all the brahmans & contemplatives in the course of the past who purified their bodily acts, verbal acts, & mental acts, did it through repeated reflection on their bodily acts, verbal acts, & mental acts in just this way.', '"all the brahmans & contemplatives in the course of the future... all the brahmans & contemplatives at present who purify their bodily acts, verbal acts, & mental acts, do it through repeated reflection on their bodily acts, verbal acts, & mental acts in just this way.', '"and so, rahula, you should train yourself: \'i will purify my bodily acts through repeated reflection.', 'i will purify my verbal acts through repeated reflection.', "i will purify my mental acts through repeated reflection.'", "that's how you should train yourself.", '"that is what the blessed one said.', 'gratified, ven.', "rahula delighted in the blessed one's words.", '0.2\n§ 2.once the blessed one was staying at kosambi in the simsapa tree grove.', 'then, picking up a few simsapa leaves with his hand, he asked the monks, "what do you think, monks: which are more numerous, the few simsapa leaves in my hand or those overhead in the simsapa grove?', '""the leaves in the hand of the blessed one are few in number, lord.', 'those overhead in the grove are far more numerous.', '""in the same way, monks, those things that i have known with direct knowledge but have not taught are far more numerous than the things i have taught.', "and why haven't i taught them?", 'because they are not connected with the goal, do not relate to the rudiments of the holy life, and do not lead to disenchantment, to dispassion, to cessation, to calm, to direct knowledge, to self-awakening, to unbinding.', 'that is why i have not taught them.', '"and what have i taught?', "'this is stress... this is the origination of stress... this is the cessation of stress... this is the path of practice leading to the cessation of stress.'", 'this is what i have taught.', 'and why have i taught these things?', 'because they are connected with the goal, relate to the rudiments of the holy life, and lead to disenchantment, to dispassion, to cessation, to calm, to direct knowledge, to self-awakening, to unbinding.', 'this is why i have taught them.', '"therefore your duty is the contemplation, \'this is stress... this is the origination of stress... this is the cessation of stress... this is the path of practice leading to the cessation of stress.\'"', '0.3\n§ 3.', '"\'stress should be known.', 'the cause by which stress comes into play should be known.', 'the diversity in stress should be known.', 'the result of stress should be known.', 'the cessation of stress should be known.', "the path of practice for the cessation of stress should be known.'", 'thus it has been said.', 'why was it said?', '"birth is stressful, aging is stressful, death is stressful; sorrow, lamentation, pain, distress, & despair are stressful; association with what is not loved is stressful, separation from what is loved is stressful, not getting what is wanted is stressful.', 'in short, the five clinging-aggregates are stressful.', '"and what is the cause by which stress comes into play?', 'craving is the cause by which stress comes into play.', '"and what is the diversity in stress?', 'there is major stress & minor, slowly fading & quickly fading.', 'this is called the diversity in stress.', '"and what is the result of stress?', 'there are some cases in which a person overcome with pain, his mind exhausted, grieves, mourns, laments, beats his breast, & becomes bewildered.', "or one overcome with pain, his mind exhausted, comes to search outside, 'who knows a way or two to stop this pain?'", 'i tell you, monks, that stress results either in bewilderment or in search.', '"and what is the cessation of stress?', 'the cessation of craving is the cessation of stress, and just this noble eightfold path is the path of practice leading to the cessation of stress: right view, right resolve, right speech, right action, right livelihood, right effort, right mindfulness, right concentration.', '"now when a disciple of the noble ones discerns stress in this way, the cause by which stress comes into play in this way, the diversity of stress in this way, the result of stress in this way, the cessation of stress in this way, & the path of practice leading to the cessation of stress in this way, then he discerns this penetrative holy life as the cessation of stress.', '"\'stress should be known.', "the cause by which stress comes into play... the variations in stress... the result of stress... the cessation of stress... the path of practice for the cessation of stress should be experienced.'", 'thus it has been said, and this is why it was said."', '0.4\n§ 4.', '"vision arose, clear knowing arose, discernment arose, knowledge arose, illumination arose within me with regard to things never heard before: \'this is the noble truth of stress... this noble truth of stress is to be comprehended... this noble truth of stress has been comprehended... this is the noble truth of the origination of stress... this noble truth of the origination of stress is to be abandoned... this noble truth of the origination of stress has been abandoned... this is the noble truth of the cessation of stress... this noble truth of the cessation of stress is to be realized... this noble truth of the cessation of stress has been realized... this is the noble truth of the path of practice leading to the cessation of stress... this noble truth of the path of practice leading to the cessation of stress is to be developed... this noble truth of the path of practice leading to the cessation of stress has been developed.', '\'"and, monks, as long as this knowledge & vision of mine — with its three rounds & twelve permutations concerning these four noble truths as they actually are — was not pure, i did not claim to have directly awakened to the unexcelled right self-awakening... but as soon as this knowledge & vision of mine — with its three rounds & twelve permutations concerning these four noble truths as they actually are — was truly pure, only then did i claim to have directly awakened to the unexcelled right self-awakening... the knowledge & vision arose in me: \'unprovoked is my release.', 'this is the last birth.', 'there is now no further becoming.', '\'"was\n0.5\n§ 5.sariputta: "there are these three forms of stressfulness, my friend: the stressfulness of pain, the stressfulness of fabrication, the stressfulness of change.', 'these are the three forms of stressfulness.', '"sariputta:\n0.6\n§ 6.sariputta: "now what, friends, is the noble truth of stress?', 'birth is stressful, aging is stressful, death is stressful; sorrow, lamentation, pain, distress, & despair are stressful; not getting what is wanted is stressful.', 'in short, the five clinging-aggregates are stressful.sariputta:"now what is birth?', 'whatever birth, taking birth, descent, coming-to-be, coming-forth, appearance of aggregates, & acquisition of sense media of the various beings in this or that group of beings, that is called birth.birth?', '"and what is aging?', 'whatever aging, decrepitude, brokenness, graying, wrinkling, decline of life-force, weakening of the faculties of the various beings in this or that group of beings, that is called aging.aging?', '"and what is death?', 'whatever deceasing, passing away, breaking up, disappearance, dying, death, completion of time, break up of the aggregates, casting off of the body, interruption in the life faculty of the various beings in this or that group of beings, that is called death.death?', '"and what is sorrow?', 'whatever sorrow, sorrowing, sadness, inward sorrow, inward sadness of anyone suffering from misfortune, touched by a painful thing, that is called sorrow.sorrow?', '"and what is lamentation?', 'whatever crying, grieving, lamenting, weeping, wailing, lamentation of anyone suffering from misfortune, touched by a painful thing, that is called lamentation.lamentation?', '"and what is pain?', 'whatever is experienced as bodily pain, bodily discomfort, pain or discomfort born of bodily contact, that is called pain.pain?', '"and what is distress?', 'whatever is experienced as mental pain, mental discomfort, pain or discomfort born of mental contact, that is called distress.distress?', '"and what is despair?', 'whatever despair, despondency, desperation of anyone suffering from misfortune, touched by a painful thing, that is called despair.despair?', '"and what is the stress of not getting what one wants?', "in beings subject to birth, the wish arises, 'o, may we not be subject to birth, and may birth not come to us.'", 'but this is not to be achieved by wishing.', 'this is the stress of not getting what one wants.', "in beings subject to aging... illness... death... sorrow, lamentation, pain, distress, & despair, the wish arises, 'o, may we not be subject to aging... illness... death... sorrow, lamentation, pain, distress, & despair, and may aging... illness... death... sorrow, lamentation, pain, distress, & despair not come to us.'", 'but this is not to be achieved by wishing.', 'this is the stress of not getting what one wants.', '"and what are the five clinging-aggregates that, in short, are stressful?', 'form as a clinging-aggregate, feeling as a clinging-aggregate, perception as a clinging-aggregate, fabrications as a clinging-aggregate, consciousness as a clinging-aggregate: these are called the five clinging-aggregates that, in short, are stressful.', '"this is called the noble truth of stress."', '0.7\n§ 7.at savatthi.', 'there the blessed one said, "monks, i will teach you the five aggregates & the five clinging-aggregates.', 'listen & pay close attention.', 'i will speak.', '""as you say, lord," the monks responded.the blessed one said, "now what, monks, are the five aggregates?', '"whatever form is past, future, or present; internal or external; blatant or subtle; common or sublime; far or near: that is called the form aggregate.', '"whatever feeling is past, future, or present; internal or external; blatant or subtle; common or sublime; far or near: that is called the feeling aggregate.', '"whatever perception is past, future, or present; internal or external; blatant or subtle; common or sublime; far or near: that is called the perception aggregate.', '"whatever (mental) fabrications are past, future, or present; internal or external; blatant or subtle; common or sublime; far or near: those are called the fabrication aggregate.', '"whatever consciousness is past, future, or present; internal or external; blatant or subtle; common or sublime; far or near: that is called the consciousness aggregate.', '"these are called the five aggregates.', '"and what are the five clinging-aggregates?', '"whatever form — past, future, or present; internal or external; blatant or subtle; common or sublime; far or near — is clingable, offers sustenance, and is accompanied with mental fermentation: that is called form as clinging-aggregate.', '"whatever feeling — past, future, or present; internal or external; blatant or subtle; common or sublime; far or near — is clingable, offers sustenance, and is accompanied with mental fermentation: that is called feeling as a clinging-aggregate.', '"whatever perception — past, future, or present; internal or external; blatant or subtle; common or sublime; far or near — is clingable, offers sustenance, and is accompanied with mental fermentation: that is called perception as a clinging-aggregate.', '"whatever (mental) fabrications — past, future, or present; internal or external; blatant or subtle; common or sublime; far or near — are clingable, offer sustenance, and are accompanied with mental fermentation: those are called fabrication as a clinging-aggregate.', '"whatever consciousness — past, future, or present; internal or external; blatant or subtle; common or sublime; far or near — is clingable, offers sustenance, and is accompanied with mental fermentation: that is called consciousness as a clinging-aggregate.', '"these are called the five clinging-aggregates."', '0.8\n§ 8.the buddha: "these are the five clinging-aggregates: form as a clinging-aggregate, feeling as a clinging-aggregate, perception as a clinging-aggregate, fabrications as a clinging-aggregate, consciousness as a clinging-aggregate... these five clinging-aggregates are rooted in desire..."the buddha:a certain monk: "is it the case that clinging and the five clinging-aggregates are the same thing, or are they separate?', '"a certain monk:the buddha: "clinging is neither the same thing as the five clinging-aggregates, nor are they separate.', 'whatever desire & passion there is with regard to the five clinging-aggregates, that is the clinging there..."the buddha:the monk: "what is the cause, what is the condition, for the discernibility of the form aggregate... feeling aggregate... perception aggregate... fabrications aggregate... consciousness aggregate?', '"the monk:the buddha: "the four great existents [the properties of earth, water, fire, & wind] are the cause & condition for the discernibility of the form aggregate.', 'contact is the cause & condition for the discernibility of the feeling... perception... fabrications aggregate.', 'name & form are the cause & condition for the discernibility of the consciousness aggregate.', '"the buddha:\n0.9\n§ 9.', '"and why do you call it \'form\' (rupa)?', "because it is afflicted (ruppati), thus it is called 'form.'", 'afflicted with what?', 'with cold & heat & hunger & thirst, with the touch of flies, mosquitoes, wind, sun, & reptiles.', 'because it is afflicted, it is called form.(rupa)?', '(ruppati),"and why do you call it \'feeling\'?', "because it feels, thus it is called 'feeling.'", 'what does it feel?', 'it feels pleasure, it feels pain, it feels neither-pleasure-nor-pain.', 'because it feels, it is called feeling.', '"and why do you call it \'perception\'?', "because it perceives, thus it is called 'perception.'", 'what does it perceive?', 'it perceives blue, it perceives yellow, it perceives red, it perceives white.', 'because it perceives, it is called perception.', '"and why do you call them \'fabrications\'?', "because they fabricate fabricated things, thus they are called 'fabrications.'", 'what do they fabricate as a fabricated thing?', 'from form-ness, they fabricate form as a fabricated thing.', 'from feeling-ness, they fabricate feeling as a fabricated thing.', 'from perception-hood...from fabrication-hood...from consciousness-hood, they fabricate consciousness as a fabricated thing.', 'because they fabricate fabricated things, they are called fabrications.', '"and why do you call it \'consciousness\'?', 'because it cognizes, thus it is called consciousness.', 'what does it cognize?', 'it cognizes what is sour, bitter, pungent, sweet, alkaline, non-alkaline, salty, & unsalty.', 'because it cognizes, it is called consciousness."', '0.10\n§ 10.mahakotthita: "feeling, perception, & consciousness: are these qualities conjoined or disjoined?', 'and is it possible, having divided them, to describe their separateness?', '"mahakotthita:sariputta: "feeling, perception, & consciousness are conjoined, not disjoined, and it is impossible, having divided them, to describe their separateness.', 'for what one feels, that one perceives; and what one perceives, that one cognizes..."\n0.11\n§ 11. form.§ 11.sariputta: "and what, friends, is form as a clinging-aggregate?', 'the four great existents and the form derived from them.', 'and what are the four great existents?', 'they are the earth-property, the water property, the fire property, & the wind property.sariputta:"and what is the earth property?', 'the earth property may be either internal or external.', 'what is the internal earth property?', 'whatever internal, belonging to oneself, is solid, solidified, & sustained: head hairs, body hairs, nails, teeth, skin, flesh, tendons, bones, bone marrow, kidneys, heart, liver, pleura, spleen, lungs, large intestines, small intestines, contents of the stomach, feces, or whatever else internally, belonging to oneself, is solid, solidified, & sustained: this is called the internal earth property.', 'now both the internal earth property and the external earth property are simply earth property.', "and that should be seen as it actually is present with right discernment: 'this is not mine, this is not me, this is not my self.'", 'when one sees it thus as it actually is present with right discernment, one becomes disenchanted with the earth property and makes the earth property fade from the mind..."and what is the water property?', 'the water property may be either internal or external.', 'what is the internal water property?', 'whatever internal, belonging to oneself, is liquid, watery, & sustained: bile, phlegm, pus, blood, sweat, fat, tears, skin-oil, saliva, mucus, oil-of-the-joints, urine, or whatever else internally, belonging to oneself, is liquid, watery, & sustained: this is called the internal water property.', 'now both the internal water property and the

In [17]:
# apply regex for the only text
import re
for i in range(len(documents)):
    documents[i] = re.sub("[^a-zA-Z]"," ",documents[i])

In [20]:
li = nltk.word_tokenize(documents[0])
li

['the',
 'buddha',
 'what',
 'do',
 'you',
 'think',
 'rahula',
 'what',
 'is',
 'a',
 'mirror',
 'for']

In [40]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()
final = []
for i in range(len(documents)):
    sentence = documents[i]
    words = nltk.word_tokenize(sentence)
    stop_words = [lem.lemmatize(word) for word in words if word not in stopwords.words('english')]
    stop_words = ' '.join(stop_words)
    final.append(stop_words)

In [41]:
final

['buddha think rahula mirror',
 'buddha rahula reflection sir',
 'rahula buddha way rahula bodily act verbal act mental act done repeated reflection buddha whenever want perform bodily act reflect bodily act want perform would lead self affliction affliction others',
 'unskillful bodily act painful consequence painful result',
 'reflection know would lead self affliction affliction others would unskillful bodily act painful consequence painful result bodily act sort absolutely unfit',
 'reflection know would cause affliction would skillful bodily act happy consequence happy result bodily act sort fit',
 'similarly verbal act mental act',
 'performing bodily act reflect bodily act leading self affliction affliction others',
 'unskillful bodily act painful consequence painful result',
 'reflection know leading self affliction affliction others give',
 'reflection know may continue',
 'similarly verbal act mental act',
 'performed bodily act reflect reflection know led self affliction affliction others unskillful bodily act painful consequence painful result confess reveal lay open teacher knowledgeable companion holy life',
 'confessed exercise restraint future',
 'reflection know lead affliction skillful bodily act happy consequence happy result stay mentally refreshed joyful training day night skillful mental quality',
 'similarly verbal act',
 'performed mental act reflect reflection know led self affliction affliction others unskillful mental act painful consequence painful result feel horrified humiliated disgusted',
 'feeling horrified exercise restraint future',
 'reflection know lead affliction skillful mental act happy consequence happy result stay mentally refreshed joyful training day night skillful mental quality',
 'rahula brahman contemplative course past purified bodily act verbal act mental act repeated reflection bodily act verbal act mental act way',
 'brahman contemplative course future brahman contemplative present purify bodily act verbal act mental act repeated reflection bodily act verbal act mental act way',
 'rahula train purify bodily act repeated reflection',
 'purify verbal act repeated reflection',
 'purify mental act repeated reflection',
 'train',
 'blessed one said',
 'gratified ven',
 'rahula delighted blessed one word',
 'blessed one staying kosambi simsapa tree grove',
 'picking simsapa leaf hand asked monk think monk numerous simsapa leaf hand overhead simsapa grove',
 'leaf hand blessed one number lord',
 'overhead grove far numerous',
 'way monk thing known direct knowledge taught far numerous thing taught',
 'taught',
 'connected goal relate rudiment holy life lead disenchantment dispassion cessation calm direct knowledge self awakening unbinding',
 'taught',
 'taught',
 'stress origination stress cessation stress path practice leading cessation stress',
 'taught',
 'taught thing',
 'connected goal relate rudiment holy life lead disenchantment dispassion cessation calm direct knowledge self awakening unbinding',
 'taught',
 'therefore duty contemplation stress origination stress cessation stress path practice leading cessation stress',
 '',
 'stress known',
 'cause stress come play known',
 'diversity stress known',
 'result stress known',
 'cessation stress known',
 'path practice cessation stress known',
 'thus said',
 'said',
 'birth stressful aging stressful death stressful sorrow lamentation pain distress despair stressful association loved stressful separation loved stressful getting wanted stressful',
 'short five clinging aggregate stressful',
 'cause stress come play',
 'craving cause stress come play',
 'diversity stress',
 'major stress minor slowly fading quickly fading',
 'called diversity stress',
 'result stress',
 'case person overcome pain mind exhausted grief mourns lament beat breast becomes bewildered',
 'one overcome pain mind exhausted come search outside know way two stop pain',
 'tell monk stress result either bewilderment search',
 'cessation stress',
 'cessation craving cessation stress noble eightfold path path practice leading cessation stress right view right resolve right speech right action right livelihood right effort right mindfulness right concentration',
 'disciple noble one discerns stress way cause stress come play way diversity stress way result stress way cessation stress way path practice leading cessation stress way discerns penetrative holy life cessation stress',
 'stress known',
 'cause stress come play variation stress result stress cessation stress path practice cessation stress experienced',
 'thus said said',
 '',
 'vision arose clear knowing arose discernment arose knowledge arose illumination arose within regard thing never heard noble truth stress noble truth stress comprehended noble truth stress comprehended noble truth origination stress noble truth origination stress abandoned noble truth origination stress abandoned noble truth cessation stress noble truth cessation stress realized noble truth cessation stress realized noble truth path practice leading cessation stress noble truth path practice leading cessation stress developed noble truth path practice leading cessation stress developed',
 'monk long knowledge vision mine three round twelve permutation concerning four noble truth actually pure claim directly awakened unexcelled right self awakening soon knowledge vision mine three round twelve permutation concerning four noble truth actually truly pure claim directly awakened unexcelled right self awakening knowledge vision arose unprovoked release',
 'last birth',
 'becoming',
 'sariputta three form stressfulness friend stressfulness pain stressfulness fabrication stressfulness change',
 'three form stressfulness',
 'sariputta sariputta friend noble truth stress',
 'birth stressful aging stressful death stressful sorrow lamentation pain distress despair stressful getting wanted stressful',
 'short five clinging aggregate stressful sariputta birth',
 'whatever birth taking birth descent coming coming forth appearance aggregate acquisition sense medium various being group being called birth birth',
 'aging',
 'whatever aging decrepitude brokenness graying wrinkling decline life force weakening faculty various being group being called aging aging',
 'death',
 'whatever deceasing passing away breaking disappearance dying death completion time break aggregate casting body interruption life faculty various being group being called death death',
 'sorrow',
 'whatever sorrow sorrowing sadness inward sorrow inward sadness anyone suffering misfortune touched painful thing called sorrow sorrow',
 'lamentation',
 'whatever cry grieving lamenting weeping wailing lamentation anyone suffering misfortune touched painful thing called lamentation lamentation',
 'pain',
 'whatever experienced bodily pain bodily discomfort pain discomfort born bodily contact called pain pain',
 'distress',
 'whatever experienced mental pain mental discomfort pain discomfort born mental contact called distress distress',
 'despair',
 'whatever despair despondency desperation anyone suffering misfortune touched painful thing called despair despair',
 'stress getting one want',
 'being subject birth wish arises may subject birth may birth come u',
 'achieved wishing',
 'stress getting one want',
 'being subject aging illness death sorrow lamentation pain distress despair wish arises may subject aging illness death sorrow lamentation pain distress despair may aging illness death sorrow lamentation pain distress despair come u',
 'achieved wishing',
 'stress getting one want',
 'five clinging aggregate short stressful',
 'form clinging aggregate feeling clinging aggregate perception clinging aggregate fabrication clinging aggregate consciousness clinging aggregate called five clinging aggregate short stressful',
 'called noble truth stress',
 'savatthi',
 'blessed one said monk teach five aggregate five clinging aggregate',
 'listen pay close attention',
 'speak',
 'say lord monk responded blessed one said monk five aggregate',
 'whatever form past future present internal external blatant subtle common sublime far near called form aggregate',
 'whatever feeling past future present internal external blatant subtle common sublime far near called feeling aggregate',
 'whatever perception past future present internal external blatant subtle common sublime far near called perception aggregate',
 'whatever mental fabrication past future present internal external blatant subtle common sublime far near called fabrication aggregate',
 'whatever consciousness past future present internal external blatant subtle common sublime far near called consciousness aggregate',
 'called five aggregate',
 'five clinging aggregate',
 'whatever form past future present internal external blatant subtle common sublime far near clingable offer sustenance accompanied mental fermentation called form clinging aggregate',
 'whatever feeling past future present internal external blatant subtle common sublime far near clingable offer sustenance accompanied mental fermentation called feeling clinging aggregate',
 'whatever perception past future present internal external blatant subtle common sublime far near clingable offer sustenance accompanied mental fermentation called perception clinging aggregate',
 'whatever mental fabrication past future present internal external blatant subtle common sublime far near clingable offer sustenance accompanied mental fermentation called fabrication clinging aggregate',
 'whatever consciousness past future present internal external blatant subtle common sublime far near clingable offer sustenance accompanied mental fermentation called consciousness clinging aggregate',
 'called five clinging aggregate',
 'buddha five clinging aggregate form clinging aggregate feeling clinging aggregate perception clinging aggregate fabrication clinging aggregate consciousness clinging aggregate five clinging aggregate rooted desire buddha certain monk case clinging five clinging aggregate thing separate',
 'certain monk buddha clinging neither thing five clinging aggregate separate',
 'whatever desire passion regard five clinging aggregate clinging buddha monk cause condition discernibility form aggregate feeling aggregate perception aggregate fabrication aggregate consciousness aggregate',
 'monk buddha four great existents property earth water fire wind cause condition discernibility form aggregate',
 'contact cause condition discernibility feeling perception fabrication aggregate',
 'name form cause condition discernibility consciousness aggregate',
 'buddha',
 'call form rupa',
 'afflicted ruppati thus called form',
 'afflicted',
 'cold heat hunger thirst touch fly mosquito wind sun reptile',
 'afflicted called form rupa',
 'ruppati call feeling',
 'feel thus called feeling',
 'feel',
 'feel pleasure feel pain feel neither pleasure pain',
 'feel called feeling',
 'call perception',
 'perceives thus called perception',
 'perceive',
 'perceives blue perceives yellow perceives red perceives white',
 'perceives called perception',
 'call fabrication',
 'fabricate fabricated thing thus called fabrication',
 'fabricate fabricated thing',
 'form ness fabricate form fabricated thing',
 'feeling ness fabricate feeling fabricated thing',
 'perception hood fabrication hood consciousness hood fabricate consciousness fabricated thing',
 'fabricate fabricated thing called fabrication',
 'call consciousness',
 'cognizes thus called consciousness',
 'cognize',
 'cognizes sour bitter pungent sweet alkaline non alkaline salty unsalty',
 'cognizes called consciousness',
 'mahakotthita feeling perception consciousness quality conjoined disjoined',
 'possible divided describe separateness',
 'mahakotthita sariputta feeling perception consciousness conjoined disjoined impossible divided describe separateness',
 'one feel one perceives one perceives one cognizes form sariputta friend form clinging aggregate',
 'four great existents form derived',
 'four great existents',
 'earth property water property fire property wind property sariputta earth property',
 'earth property may either internal external',
 'internal earth property',
 'whatever internal belonging oneself solid solidified sustained head hair body hair nail teeth skin flesh tendon bone bone marrow kidney heart liver pleura spleen lung large intestine small intestine content stomach feces whatever else internally belonging oneself solid solidified sustained called internal earth property',
 'internal earth property external earth property simply earth property',
 'seen actually present right discernment mine self',
 'one see thus actually present right discernment one becomes disenchanted earth property make earth property fade mind water property',
 'water property may either internal external',
 'internal water property',
 'whatever internal belonging oneself liquid watery sustained bile phlegm pu blood sweat fat tear skin oil saliva mucus oil joint urine whatever else internally belonging oneself liquid watery sustained called internal water property',
 'internal water property external water property simply water property',
 'seen actually present right discernment mine self',
 'one see thus actually present right discernment one becomes disenchanted water property make water property fade mind fire property',
 'fire property may either internal external',
 'internal fire property',
 'whatever internal belonging oneself fire fiery sustained one warmed age waste away eaten drunk consumed tasted get completely digested whatever else internally belonging oneself fire fiery sustained called internal fire property',
 'internal fire property external fire property simply fire property',
 'seen actually present right discernment mine self',
 'one see thus actually present right discernment one becomes disenchanted fire property make fire property fade mind wind property',
 'wind property may either internal external',
 'internal wind property',
 'whatever internal belonging oneself wind windy sustained going wind going wind wind stomach wind intestine wind course body breathing whatever else internally belonging oneself wind windy sustained called internal wind property',
 'internal wind property external wind property simply wind property',
 'seen actually present right discernment mine self',
 'one see thus actually present right discernment one becomes disenchanted wind property make wind property fade mind feeling sister dhammadinna three kind feeling pleasant feeling painful feeling neither pleasant painful feeling whatever experienced physically mentally pleasant gratifying pleasant feeling',
 'whatever experienced physically mentally painful hurting painful feeling',
 'whatever experienced physically mentally neither gratifying hurting neither pleasant painful feeling pleasant feeling pleasant remaining painful changing',
 'painful feeling painful remaining pleasant changing',
 'neither pleasant painful feeling pleasant conjoined knowledge painful devoid knowledge',
 'sister dhammadinna fabrication',
 'fabrication',
 'six class intention intention aimed sight sound aroma taste tactile sensation idea',
 'called fabrication',
 '',
 'sister dhammadinna breathing bodily bound body therefore called bodily fabrication',
 'directed one thought evaluated matter one break speech',
 'therefore directed thought evaluation called verbal fabrication',
 'perception feeling mental bound mind',
 'therefore perception feeling called mental fabrication',
 'sister dhammadinna bodily fabrication verbal fabrication mental fabrication',
 'consciousness',
 'consciousness classified simply condition dependence arises',
 'consciousness arises dependence eye form classified simply eye consciousness',
 'consciousness arises dependence ear sound classified simply ear consciousness',
 'consciousness arises dependence nose smell classified simply nose consciousness',
 'consciousness arises dependence tongue taste classified simply tongue consciousness',
 'consciousness arises dependence body tactile sensation classified simply body consciousness',
 'consciousness arises dependence intellect idea classified simply intellect consciousness',
 '',
 'noble truth origination stress',
 'craving make becoming accompanied passion delight relishing e craving sensuality craving becoming craving non becoming noble truth cessation stress',
 'remainderless fading cessation renunciation relinquishment release letting go craving',
 '',
 'noble method rightly seen rightly ferreted discernment',
 'case disciple noble one notice',
 'arising come arising',
 '',
 'cessation come cessation',
 'ignorance condition fabrication',
 'fabrication condition consciousness',
 'consciousness condition name form',
 'name form condition six sense sphere',
 'six sense sphere condition contact',
 'contact condition feeling',
 'feeling condition craving',
 'craving condition clinging sustenance',
 'clinging sustenance condition becoming',
 'becoming condition birth',
 'birth condition old age death sorrow lamentation pain distress despair come play',
 'origination entire mass stress suffering',
 'remainderless fading cessation ignorance cessation fabrication',
 'cessation fabrication cessation consciousness',
 'cessation consciousness cessation name form',
 'cessation name form cessation six sense sphere',
 'cessation six sense sphere cessation contact',
 'cessation contact cessation feeling',
 'cessation feeling cessation craving',
 'cessation craving cessation clinging sustenance',
 'cessation clinging sustenance cessation becoming',
 'cessation becoming cessation birth',
 'cessation birth old age death sorrow lamentation pain distress despair cease',
 'cessation entire mass stress suffering',
 'noble method rightly seen rightly ferreted discernment',
 'sariputta blessed one said whoever see dependent co arising see dhamma whoever see dhamma see dependent co arising',
 'sariputta',
 'first knowledge steadfastness dhamma dependent co arising knowledge unbinding',
 '',
 'becoming',
 'three becomings sensual becoming form becoming formless becoming',
 'called becoming becoming',
 'clinging sustenance',
 'four clingings sensuality clinging view clinging precept practice clinging doctrine self clinging',
 'called clinging clinging sustenance',
 'craving',
 'six class craving craving form craving sound craving smell craving taste craving tactile sensation craving idea',
 'called craving craving',
 'feeling',
 'six class feeling feeling born eye contact feeling born ear contact feeling born nose contact feeling born tongue contact feeling born body contact feeling born intellect contact',
 'called feeling feeling',
 'contact',
 'six class contact eye contact ear contact nose contact tongue contact body contact intellect contact',
 'called contact contact',
 'six sense sphere',
 'six sense sphere eye sphere ear sphere nose sphere tongue sphere body sphere intellect sphere',
 'called six sense sphere six sense sphere',
 'name form',
 'feeling perception intention contact attention called name',
 'four great element form dependent four great element called form',
 'name form called name form name form',
 'consciousness',
 'six class consciousness eye consciousness ear consciousness nose consciousness tongue consciousness body consciousness intellect consciousness',
 'called consciousness consciousness',
 'fabrication',
 'three fabrication bodily fabrication verbal fabrication mental fabrication',
 'called fabrication fabrication',
 'ignorance',
 'knowing stress knowing origination stress knowing cessation stress knowing way practice leading cessation stress called ignorance ignorance',
 '',
 'ending fermentation one know see tell one know see',
 'one know see',
 'form origination disappearance',
 'feeling perception fabrication consciousness origination disappearance',
 'ending fermentation one know way see way',
 'knowledge ending presence ending prerequisite tell',
 'without prerequisite',

In [42]:
len(final)

6197

In [46]:
# bagof words
from sklearn.feature_extraction.text import CountVectorizer

cv  = CountVectorizer(binary = False,ngram_range = (1,2))

x= cv.fit_transform(final)

In [47]:
x[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], shape=(1, 49543))

In [49]:
df = pd.DataFrame(x.toarray(),columns = cv.get_feature_names_out())

In [50]:
df

,aaron,aaron brother,aaron gave,aaron glory,aaron shouted,aaron thy,abandon,abandon passion,abandon wrong,abandoned,...,youth wink,youth worldly,youthful,youthful teacher,zeal,zeal evil,zeal good,zeal take,zorobabel,zorobabel jesus
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6192,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6193,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6194,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6195,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6196,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [57]:
# Tf-idf 
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(ngram_range=(1,2))

data = tfidf.fit_transform(final)

In [58]:
data.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(6197, 49543))

In [59]:
data = pd.DataFrame(data.toarray(),columns = tfidf.get_feature_names_out())

In [60]:
data

,aaron,aaron brother,aaron gave,aaron glory,aaron shouted,aaron thy,abandon,abandon passion,abandon wrong,abandoned,...,youth wink,youth worldly,youthful,youthful teacher,zeal,zeal evil,zeal good,zeal take,zorobabel,zorobabel jesus
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6192,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6193,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
import requests

url = "https://real-time-amazon-data.p.rapidapi.com/influencer-profile"

querystring = {"influencer_name":"tastemade","country":"US"}

headers = {
	"x-rapidapi-key": "f343660461msh8e730a1b19e9e9cp1d48ffjsn0cb4cb4d2470",
	"x-rapidapi-host": "real-time-amazon-data.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'status': 'OK', 'request_id': '4636c4a5-90b2-4748-9493-0274773c094b', 'parameters': {'influencer_name': 'tastemade', 'country': 'US', 'language': 'en_US'}, 'data': {'name': 'Tastemade', 'country': 'US', 'domain': 'www.amazon.com', 'profile_description': 'A global community of food, travel and home & design enthusiasts.', 'profile_link': 'https://www.amazon.com/shop/tastemade', 'is_top_creator': True, 'affiliate_status': 'Earns commissions', 'has_curations': False, 'posts_count': 3082}}

In [11]:
response.json()

{'status': 'OK',
 'request_id': '4636c4a5-90b2-4748-9493-0274773c094b',
 'parameters': {'influencer_name': 'tastemade',
  'country': 'US',
  'language': 'en_US'},
 'data': {'name': 'Tastemade',
  'country': 'US',
  'domain': 'www.amazon.com',
  'profile_description': 'A global community of food, travel and home & design enthusiasts.',
  'profile_link': 'https://www.amazon.com/shop/tastemade',
  'is_top_creator': True,
  'affiliate_status': 'Earns commissions',
  'has_curations': False,
  'posts_count': 3082}}

In [12]:
print(response.json().keys())

dict_keys(['status', 'request_id', 'parameters', 'data'])

In [14]:
import pandas as pd
df = pd.DataFrame(response.json())

In [15]:
df

,status,request_id,parameters,data
influencer_name,OK,4636c4a5-90b2-4748-9493-0274773c094b,tastemade,NaN
country,OK,4636c4a5-90b2-4748-9493-0274773c094b,US,US
language,OK,4636c4a5-90b2-4748-9493-0274773c094b,en_US,NaN
name,OK,4636c4a5-90b2-4748-9493-0274773c094b,NaN,Tastemade
domain,OK,4636c4a5-90b2-4748-9493-0274773c094b,NaN,www.amazon.com
profile_description,OK,4636c4a5-90b2-4748-9493-0274773c094b,NaN,"A global community of food, travel and home & ..."
profile_link,OK,4636c4a5-90b2-4748-9493-0274773c094b,NaN,https://www.amazon.com/shop/tastemade
is_top_creator,OK,4636c4a5-90b2-4748-9493-0274773c094b,NaN,True
affiliate_status,OK,4636c4a5-90b2-4748-9493-0274773c094b,NaN,Earns commissions
has_curations,OK,4636c4a5-90b2-4748-9493-0274773c094b,NaN,False
posts_count,OK,4636c4a5-90b2-4748-9493-0274773c094b,NaN,3082